apiVersion: v1
kind: Pod
metadata:
  name: mytestpod2
spec: # Pod spec
  containers:
      - name: mytestcontainer2
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379
