apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: centos
        image: centos:latest
