apiVersion: v1
kind: Pod
metadata:
  name: nginx-service-pod
  labels:
    app: webserver
spec:
  containers:
  - name: nginx-cont
    labels:
      app: webserver
    image: nginx:latest
    ports:
      - containerPort: 80
